
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const LOGOUT = 'LOGOUT';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const LOADING = 'LOADING';
export const NOT_LOADING = 'NOT_LOADING';
export const FETCH_ARRIVALS_SUCCESS = 'FETCH_ARRIVALS_SUCCESS';
export const FETCH_ARRIVALS_FAIL = 'FETCH_ARRIVALS_FAIL';
export const FETCH_DEPARTURES_SUCCESS = 'FETCH_DEPARTURES_SUCCESS';
export const FETCH_DEPARTURES_FAIL = 'FETCH_DEPARTURES_FAIL';